name: Trigger auto deployment for container-app-oa6ekul7gwupc

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'server/**'
    - '.github/workflows/container-app-oa6ekul7gwupc-AutoDeployTrigger-9933fa8a-5be3-47fc-b9cf-0555d041e87d.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPOA6EKUL7GWUPC_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPOA6EKUL7GWUPC_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPOA6EKUL7GWUPC_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/server 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPOA6EKUL7GWUPC_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPOA6EKUL7GWUPC_REGISTRY_PASSWORD }}
          containerAppName: container-app-oa6ekul7gwupc
          resourceGroup: todonodejspgsqlgoogleauth8a6c8687
          imageToBuild: default/container-app-oa6ekul7gwupc:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


